package com.zgsy.bs.user.impl.serivce;

import com.alibaba.dubbo.config.annotation.Service;
import com.zgsy.bs.user.impl.dao.ProjectTaskDao;
import com.zgsy.bs.user.model.ProjectTask;
import com.zgsy.bs.user.service.ProjectTaskReadService;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;

import java.util.List;

/**
 * Code generated by CodeGen
 * Desc: 项目任务表读服务实现类
 * Date: 2017-01-14
 */
@Slf4j
@Service(version = "1.0.0")
public class ProjectTaskReadServiceImpl implements ProjectTaskReadService {
    @Autowired
    private  ProjectTaskDao projectTaskDao;

    @Override
    public ProjectTask findById(Long taskId) {
        return projectTaskDao.findById(taskId);
    }

    @Override
    public List<ProjectTask> findByUserId(Long userId) {
        return null;
    }

    @Override
    public List<ProjectTask> findByGroupId(Long groupId) {
        return null;
    }

    @Override
    public List<ProjectTask> findChildTasks(Long parentId) {
        return projectTaskDao.findChildTasks(parentId);
    }

    @Override
    public List<ProjectTask> findProjectModels(Long projectId) {
        return projectTaskDao.findProjectModels(projectId);
    }

    @Override
    public List<ProjectTask> findChildTaskByParentIdAndStatus(Long parentId, Integer status) {
        return projectTaskDao.findChildTaskByParentIdAndStatus(parentId,status);
    }

    @Override
    public List<ProjectTask> findAll() {
        return projectTaskDao.findAll();
    }


}
