package com.zgsy.bs.user.impl.dao;
import com.zgsy.bs.common.dao.MyBatisDao;
import com.zgsy.bs.user.model.UserPost;
import org.springframework.stereotype.Repository;


/**
 * Code generated by CodeGen
 * Desc: 用户帖子Dao类
 * Date: 2017-05-14
 */
@Repository
public class UserPostDao extends MyBatisDao<UserPost> {

    public UserPostDao() {
        super("user.post");
    }
}
